In [1]:
import numpy as np  # Creating alias np for numpy

In [2]:
# numpy is for numerical calculation 
# it stores data in grid (arrays)

np.array([1,3,5,6,4,34,4])   #1 D Array\



array([ 1,  3,  5,  6,  4, 34,  4])

In [3]:
x=np.array([[1,2,3,4,],[1,12,2,5]])

In [4]:
x                                            # printing matrix

array([[ 1,  2,  3,  4],
       [ 1, 12,  2,  5]])

In [5]:
x[1][2]       # accessing elements

2

In [6]:
x[1,1]

12

In [25]:
c=np.array([[1,2,4,56,56],[12,45,67,89,34],[23,45,54,65,67],[23,45,33,22,88]])

In [26]:
c

array([[ 1,  2,  4, 56, 56],
       [12, 45, 67, 89, 34],
       [23, 45, 54, 65, 67],
       [23, 45, 33, 22, 88]])

In [42]:
#c1:3,1:3]
x[:3,1:3]       #no need to mention start
#[:3,1:]         

array([[ 2,  3],
       [12,  2]])

In [40]:
c


array([[ 1,  2,  4, 56, 56],
       [12, 45, 67, 89, 34],
       [23, 45, 54, 65, 67],
       [23, 45, 33, 22, 88]])

In [28]:
c.T  # transpose of matrix

array([[ 1, 12, 23, 23],
       [ 2, 45, 45, 45],
       [ 4, 67, 54, 33],
       [56, 89, 65, 22],
       [56, 34, 67, 88]])

In [17]:
a=np.array([list([12,2,3,423,3]), list([1,3,4,5,6]),list([7,6,5,4,5]),
       list([2,3,4,5,6])

SyntaxError: unexpected EOF while parsing (1743229181.py, line 2)

In [50]:
a


array([[ 12,   2,   3, 423,   3],
       [  1,   3,   8,   9,   6],
       [  7,   6,   2,   1,   6],
       [  2,   3,   4,   5,   6]])

In [51]:
b=np.array([[2,34,5,67,7],[23,34,45,67,89],[45,32,43,55,78],[1,45,67,89,76]])

In [52]:
b

array([[ 2, 34,  5, 67,  7],
       [23, 34, 45, 67, 89],
       [45, 32, 43, 55, 78],
       [ 1, 45, 67, 89, 76]])

In [53]:
a+b

array([[ 14,  36,   8, 490,  10],
       [ 24,  37,  53,  76,  95],
       [ 52,  38,  45,  56,  84],
       [  3,  48,  71,  94,  82]])

In [54]:
a==b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [55]:
a*b

array([[   24,    68,    15, 28341,    21],
       [   23,   102,   360,   603,   534],
       [  315,   192,    86,    55,   468],
       [    2,   135,   268,   445,   456]])

In [56]:
a/b

array([[6.        , 0.05882353, 0.6       , 6.31343284, 0.42857143],
       [0.04347826, 0.08823529, 0.17777778, 0.13432836, 0.06741573],
       [0.15555556, 0.1875    , 0.04651163, 0.01818182, 0.07692308],
       [2.        , 0.06666667, 0.05970149, 0.05617978, 0.07894737]])

In [57]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.empty_like(a)

array([[4618441417868443648, 4588638185040256542, 4603579539098121011,
        4618794311869095814, 4601392076421969627],
       [4586426698778222948, 4591022443666511511, 4595573139760573463,
        4594007709442336554, 4589522235991564564],
       [4594772499826818708, 4595923419731591168, 4586863853039322612,
        4580897773702091422, 4590207312512236308],
       [4611686018427387904, 4589468260265693457, 4588764712861218663,
        4588257179916460492, 4590353178087211870]])

In [62]:
np.who


<function numpy.lib.utils.who(vardict=None)>

In [63]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [65]:
np.who


<function numpy.lib.utils.who(vardict=None)>

In [70]:
a[[0,2,1],[1,2,0]]

array([2, 2, 1])

In [68]:
np.random.random((3,3))

array([[0.43812614, 0.40942407, 0.18934408],
       [0.37572902, 0.30946874, 0.33055167],
       [0.80900141, 0.620537  , 0.73101228]])

In [71]:
w = np.array([[10,20,30],[40,50,60],[10,44,33]])

In [72]:
w

array([[10, 20, 30],
       [40, 50, 60],
       [10, 44, 33]])

In [73]:
w > 5  #creates a array of true false
w[w>5]  # createw elements array all greater than 5

array([10, 20, 30, 40, 50, 60, 10, 44, 33])

In [74]:
w>5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [76]:
np.add(a,b)


array([[ 14,  36,   8, 490,  10],
       [ 24,  37,  53,  76,  95],
       [ 52,  38,  45,  56,  84],
       [  3,  48,  71,  94,  82]])

In [77]:
np.subtract(a,b)

array([[ 10, -32,  -2, 356,  -4],
       [-22, -31, -37, -58, -83],
       [-38, -26, -41, -54, -72],
       [  1, -42, -63, -84, -70]])

In [78]:
np.multiply(a,b)

array([[   24,    68,    15, 28341,    21],
       [   23,   102,   360,   603,   534],
       [  315,   192,    86,    55,   468],
       [    2,   135,   268,   445,   456]])

In [79]:
np.divide(a,b)

array([[6.        , 0.05882353, 0.6       , 6.31343284, 0.42857143],
       [0.04347826, 0.08823529, 0.17777778, 0.13432836, 0.06741573],
       [0.15555556, 0.1875    , 0.04651163, 0.01818182, 0.07692308],
       [2.        , 0.06666667, 0.05970149, 0.05617978, 0.07894737]])

In [80]:
np.sqrt(a)

array([[ 3.46410162,  1.41421356,  1.73205081, 20.5669638 ,  1.73205081],
       [ 1.        ,  1.73205081,  2.82842712,  3.        ,  2.44948974],
       [ 2.64575131,  2.44948974,  1.41421356,  1.        ,  2.44948974],
       [ 1.41421356,  1.73205081,  2.        ,  2.23606798,  2.44948974]])

In [86]:
np.mod(a,b)

array([[ 0,  2,  3, 21,  3],
       [ 1,  3,  8,  9,  6],
       [ 7,  6,  2,  1,  6],
       [ 0,  3,  4,  5,  6]])

In [85]:
a

array([[ 12,   2,   3, 423,   3],
       [  1,   3,   8,   9,   6],
       [  7,   6,   2,   1,   6],
       [  2,   3,   4,   5,   6]])

In [87]:
np.sum(a,axis=1)      #column wise row addition 

array([443,  27,  22,  20])

In [88]:
np.sum(a,axis=0)        #row wise column addition

array([ 22,  14,  17, 438,  21])

In [89]:
a

array([[ 12,   2,   3, 423,   3],
       [  1,   3,   8,   9,   6],
       [  7,   6,   2,   1,   6],
       [  2,   3,   4,   5,   6]])

In [92]:
a=a[:2,:]

In [93]:
a

array([[ 12,   2,   3, 423,   3],
       [  1,   3,   8,   9,   6]])

In [97]:
np.reshape(a,(5,2))

array([[ 12,   2],
       [  3, 423],
       [  3,   1],
       [  3,   8],
       [  9,   6]])

In [98]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])